name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: format
        run: make format
      - name: lint
        run: make lint
      - name: test
        run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: build   # solo se ejecuta si build pasa
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4 
        with:
          submodules: recursive

      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-main:latest
          file: ./Dockerfile
      
      - name: Trigger Render Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d3sdsj15pdvs73e3dmeg?key=${{ secrets.RENDER_DEPLOY_HOOK_KEY }}"
  hf:
    runs-on: ubuntu-latest
    needs: build   # solo se ejecuta si build pasa
    steps:
      - name: Checkout repository with all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necesario para acceder a otras ramas (hf-space)
          ref: main
      
      - name: Switch to hf-space branch
        run: |
          git fetch origin hf-space
          git checkout hf-space
      
      - name: Add Hugging Face remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: git remote add huggingface https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/MLOps-Lab2-demo.git

      - name: Push hf-space branch to Hugging Face
        run: git push huggingface hf-space:main --force