name: Deploy Gradio app to Hugging Face Space

on:
  push:
    branches:
      - main
    paths:
      - "app.py"           # solo se ejecuta si cambia app.py
      - "requirements.txt"  # o requirements.txt
      - ".github/workflows/deploy-to-hf.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Authenticate with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git clone https://${secrets.HF_USERNAME}:${secrets.HF_TOKEN}@huggingface.co/spaces/${secrets.HF_USERNAME}/MLOps-Lab2-demo hf-space
          cp app/app.py hf-space/
          cp app/requirements.txt hf-space/
          cd hf-space
          git add app.py requirements.txt
          git commit -m "Update app.py and requirements.txt automatically from GitHub Actions" || echo "No changes to commit"
          git push origin main
