name: Build and push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4 
        with:
          submodules: recursive

      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-main:latest
          file: ./Dockerfile
      
      - name: Trigger Render Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d3sdsj15pdvs73e3dmeg?key=${{ secrets.RENDER_DEPLOY_HOOK_KEY }}"